name: Test Enov8 Send Environment Info

on:
  workflow_dispatch:

jobs:
  enov8-test:
    runs-on: ubuntu-latest
    environment: production  # ✅ Uses your GitHub Environment for secrets
    env:
      ENOV8_APP_ID: ${{ secrets.ENOV8_APP_ID }}
      ENOV8_APP_KEY: ${{ secrets.ENOV8_APP_KEY }}
      ENOV8_BASE_URL: ${{ secrets.ENOV8_BASE_URL }}
    steps:
      - name: Checkout Code (optional)
        uses: actions/checkout@v4

      - name: Send to Enov8
        uses: hpashok24/enov8-send-environment-action@v1.2  # ✅ Correct repo and tag
        with:
          version: "17.26"
          system: "GDW"
          environment: "DEV Env"
